### ISSUE TITLE
Connecteur canopsis/shinken plus fonctionnel

### ISSUE THREAD

**Issue by floppy84** [capensis/canopsis#190]
Je tente de réactiver le module canopsis dans shinken mais cela provoque une charge mémoire et Swap énorme sur le serveur jusqu' la faire s'écrouler ou que le system décide de lui même de kiler un process pour survivre.

Ce problème se produit uniquement lorsque j'active le module canopsis au niveau du broker.

j'ai fait un snapshoot de ma vm canopsis, ensuite j'ai fait une purge totale de canopsis et une nouvelle installation.
J'ai ensuite tenté de remettre le connecteur canopsis de shinken en fonction.

Résultat : toujours le problème de surcharge de la ram et du swap.
Le connecteur Canopsis ne fonctionne donc plus avec l'update ficus indépendamment de mes précédentes données stocké dans canopsis.

**Comment by david-guenault** [comment]
Salut @floppy84 désolé pour le délai mais je ne maintient plus activement le connecteur (plus d'utilisation de canopsis de mon côté). En plus cela à tellement changé que je ne vois pas trop par quel bout le prendre ;-)
