### ISSUE TITLE
[Résolu] Compréhension bac à événement

### ISSUE THREAD

**Issue by gcoeugnet** [capensis/canopsis#227]
Bonjour,

Je me permets d'ouvrir un nouveau ticket ici bien que je conçois que ce ne soit pas le meilleur endroit. En effet, j'ai toujours des soucis pour m'enregistrer sur le forum monitoring-fr.org. Je ne reçois pas les mails de confirmation de création de compte. Après avoir parcouru sans succès le forum en quête d'une adresse mail pour prévenir de cette anomalie, j'ai vu que @rfronteau en été le modérateur et qu'il faisait partie de la communauté Gitgub. S'il lit ce message ou si quelqu'un le connaissant pouvait le prévenir, je vous en serait reconnaissant.

J'essai de prendre en main canopsis (version communautaire) en parcourant les articles/doc que je peux trouver çà et là. Mon objectif et de créer un transport pour faire communiquer l'outil de supervision réseau libreNMS avec Canopsis. J'ai donc utilisé l'exemple de code de génération d'événement fourni [ici](http://www.canopsis.org/wp-content/themes/canopsis/doc/sakura/developer-guide/events/send-event-with-php.html). L'event généré est visiblement bien formatté (voir ci-dessous), il apparait dans la log : archiver.log et je vois apparaitre plusieurs entités correspondantes dans l'onglet "Engine->Context" de Canopsis. Mais, rien dans le bac à événement alors que la sévérité est à 1. Pourriez-vous m'expliquer pourquoi svp ? 

```
root@librenms:~# php -f test.php
JSON Event:  {"timestamp":1457427315,"connector":"cli","connector_name":"LibreNMS","event_type":"log","source_type":"resource","component":"librenms","resource":"event_test","state":1,"state_type":1,"output":"TEST","display_name":"librenms_test"}
Routing-key: cli.LibreNMS.log.resource.librenms.event_test
```

**Comment by linkdd** [comment]
Bonjour,

Pour remonter un event dans le bac à événement, il faut que cet event ait un ``event_type = "check"``, ici tu utilises ``log`` donc l'event est historisé mais rien n'est fait avec.

**Comment by gcoeugnet** [comment]
Ok, merci bien pour cette réponse rapide. Je vais me mettre en quête d'infos sur les différents types d'events et leur impact. 

Merci bcp et bonne journée.

**Comment by linkdd** [comment]
La documentation sur readthedocs n'est pas encore à jour (nous sommes en train de préparer une nouvelle version et la doc sera mise à jour en conséquence.

Pour avoir la spec actuelle il faut aller directement dans les sources de la documentation : 

https://git.canopsis.net/canopsis/canopsis/blob/develop/doc/sakura/FR/fr__event.rst

**Comment by gcoeugnet** [comment]
Merci ! J'étais déjà tombé sur [cette page](http://www.canopsis.org/wp-content/themes/canopsis/doc/sakura/user-guide/event-spec.html) mais j'avais pas pigé qu'en fonction du type d'évènement, l'event apparaitrait ou non dans la console. Après changement de log en check l'event apparait bien, je vais voir pour me lancer dans le dev du transport libreNMS pour qu'il puisse remonter ces alertes dans Canopsis. Ca pourrait servir à d'autre...

**Comment by rfronteau** [comment]
Bonjour,

Je viens de voir ton message et je vais regarder ce qu il y a côté forum.

Ton association libreNMS et Canopsis à l air d etre pas mal.

Il serait intéressant que tu puisses faire connaître cette solution via un
article de blog qu en penses tu ?

**Comment by rfronteau** [comment]
Mon émail communautaire est rfronteau@cfsl-asso.org si tu veux qu on en
parle.

Le mar. 8 mars 2016 18:51, Romuald Fronteau <rfronteau@cfsl-asso.org> a
écrit :

> Bonjour,
>
> Je viens de voir ton message et je vais regarder ce qu il y a côté forum.
>
> Ton association libreNMS et Canopsis à l air d etre pas mal.
>
> Il serait intéressant que tu puisses faire connaître cette solution via un
> article de blog qu en penses tu ?
>

**Comment by linkdd** [comment]
En fait, on a déjà un connecteur librenms2canopsis qui a été fait, il n'est pas encore disponible dans la partie OpenSource du projet (je ne sais pas s'il a vocation à l'être d'ailleurs).

Je reviens vers vous sur cette issue dès que j'en sais plus.

**Comment by gcoeugnet** [comment]
Bonjour,

Puisque libreNMS est libre, qu'il existe une version communautaire de canopsis, il ne tardera pas à avoir une version du transport librenms->canopsis libre. C'est du PHP, il n'y a rien de techniquement impossible, il faut juste du temps pour le faire. Côté libreNMS, ils ne sont pas contre pour les avoir déjà sondés.

**Comment by gcoeugnet** [comment]
J'ai fait quelques lignes de codes pour permettre à libreNMS de causer avec Canopsis. En l'état, çà fonctionne, je me suis basé sur le code indiqué [ici](https://github.com/capensis/canopsis/wiki/Send-Event-with-PHP). C'est perfectible, je ne suis pas développeur à la base. C'est un début de version open source puisque le plugin de capensis n'a pas forcément vocation à l'être. Avant de le publié j'ai vu avec un directeur de projet chez capensis voir si c'était génant de le publier, ce à quoi il m'a répondu que non.

Voir [ici](https://github.com/librenms/librenms/pull/3299). Reste aux contributeurs de libreNMS de l'accepter ou pas.
