### ISSUE TITLE
Où peut-on télécharger le rpm canopsis-cat-2.5.16-1.e17.centos.x86_64.rpm

### ISSUE THREAD

**Issue by merouaneagar** [capensis/canopsis#240]
Bonjour,

J'ai vue qu'on pouvez faire une installation a partir du rpm, mais je ne trouve aucun endroit ou peut-on le télécharger.

Cordialement,
Merouane AGAR

**Comment by arctarus44** [comment]
Bonjour,

Premièrement, canopsis-cat est la version non libre de canopsis, il faut donc l'acheter.

Deuxièmement, pourquoi souhaitez-vous installer une ancienne version de canopsis ?

Pour finir, il n'y a pas de paquets disponible pour cette version. L'installation par paquet est très recente

Si tu souhaites installer canopsis 2.5.16, tu peux soit utiliser le script ``build-install.sh`` ou passer par ``docker``.

Cordialement

**Comment by merouaneagar** [comment]
Merci grand chef
